server:
  port: 8095
  servlet:
    context-path: /${spring.application.name}
spring:
  application:
    name: core-service
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      timeout: 600ms
      host: ${REDIS_HOST_CORE:localhost}
      port: ${REDIS_PORT:6379}

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5438/postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/changelog/liquibase-changelog.xml
    database-change-log-table: changelog_${spring.application.name}
    database-change-log-lock-table: changelog_lock_${spring.application.name}

  cloud:
    discovery:
      client:
        simple:
          order: 0
          instances:
            auth-service:
              - uri: ${AUTH_SERVICE:http://localhost:8080}
            admin-service:
              - uri: ${ADMIN_SERVICE:http://localhost:8110}
            connector-handler-service:
              - uri: ${CONNECTOR_HANDLER_SERVICE:http://localhost:8097}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

scheduler:
  save-transactions: 10000

elasticsearch:
  host: ${ELASTICSEARCH_HOST_CORE:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elastic}

index-prefixes:
  user: user

redis-prefixes:
  transaction: transactions:counter
  model-rule: model:rule
  counter-requests-core: counter:requests:core
  amount-of-transactions: amount:transaction
  amount-of-transaction-errors: amount:transaction:error
  model-struct-response: model:struct:response

management:
  endpoints:
    web:
      exposure:
        include: caches

springdoc:
  swagger-ui:
    enabled: true
    config-url: /${spring.application.name}/v3/api-docs/swagger-config
    url: /${spring.application.name}/v3/api-docs

logging:
  level:
    org.springframework: WARN

app.version: '@project.version@'
connection:
  allowed-origin: ${ALLOWED_URL:http://localhost:3000}